version: '2'
services:
    web:
        restart: always
        image: php:7.0-apache
        volumes:
            - $VHOST_VOLUME:/etc/apache2/sites-available
            - $SRC_VOLUME:/var/www/html
        environment:
            - VIRTUAL_HOST=$VIRTUAL_HOST
    reverse-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
            - $PROXY_HTTP_PORT:80/tcp
            - $PROXY_HTTPS_PORT:443/tcp
        volumes:
            - $DOCKER_SOCK:/tmp/docker.sock:ro